ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS app_version TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS bundle_version TEXT NOT NULL DEFAULT 'none';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS outcome_code TEXT NOT NULL DEFAULT 'success';
